package:
  name: climate4r
  version: 1.1.0

build:
  script_env:
    - GITHUB_PAT

requirements:
  build:
    - r-base>=3.6.2
    - openjdk<9
    - gdal
    - xorg-libxt
    - udunits2
    - curl
    - zstd>=1.4.4
    - libv8
    - jq
    - protobuf
    - geojson
  run:
    - r-base>=3.6.2
    - openjdk<9
    - gdal
    - xorg-libxt
    - udunits2
    - curl
    - zstd>=1.4.4
    - libv8
    - jq
    - protobuf
    - geojson

about:
  home: https://github.com/SantanderMetGroup/climate4R
